trigger:
- main

variables:
  dockerRegistryServiceConnection: '50403604-a3cd-4c99-8c15-a5df9424c91c'  # Your service connection ID
  imageRepository: 'maheshtetrisgameapp'  # Your image name in ACR
  containerRegistry: 'testris.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: Default  # Must match your self-hosted agent pool name

steps:
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    command: buildAndPush
    Dockerfile: $(dockerfilePath)
    tags: |
      $(tag)
