trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '50403604-a3cd-4c99-8c15-a5df9424c91c'  # Service connection name or ID
  imageRepository: 'maheshtetrisgameapp'  # Just the repo name
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)  # Use Microsoft-hosted Ubuntu agent
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
          latest
